### ISSUE TITLE
Try uploading Contentful data to Strapi

### ISSUE THREAD

**Issue by guidolarosa** [Coyote-Web-Studio/contentful-2-strapi-migration-tool#2]
In order to perform the CMS migration successfully, first we need to try migrating the content from Contentful to Strapi, and see what issues arise from this process.

**Comment by guidolarosa** [comment]
My first attempt at doing this was successful. I used a minimal version of the content model on the new Strapi I created for testing purposes using the data exported from Contentful. I will be tweaking the migration tool so we can ideally export all the fields from the original entries to Strapi.

**Comment by Cherna** [comment]
💪
